# Generated by Django 5.0.6 on 2024-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='Null', upload_to='images'),
        ),
    ]
