# Generated by Django 5.0.6 on 2024-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='jobtitle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
